### ISSUE TITLE
draggable nodes under an area path cannot be dragged

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#34]
http://localhost:5000/#area

try dragging a node underneath an area layer. won't budge...

**Comment by sanchan** [comment]
# Paste an explanation from hipchat:

the problem is there isn't a "z-index" alternative in svg

so

the "svg's z-index" is the rendering order of each object

so if "b" is rendered after "a"

b is over a

so

when a Rendered is rendered, every circle is rendered inside its own <g> element

so

when the area of the second line is over the circles of the first line

if you select with firebug, you can see what I mean

solution:

create a new svg layer for circles only

or

a new layer for each Renderer, this way each Renderer is going to have (at least) 2 layers:

1) for line and area

2) for circles

but

the circles layers MUST be rendered AFTER every line-area layer

I think is not very easy

because

we need to recalculte each point

because (but I'm not completly sure) each circle is rendered relative to its current <g> layer
